# Generated by Django 4.2.1 on 2023-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
            ],
        ),
    ]
